export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

// export const PROMPT_FIELD_ERRORS = 'PROMPT_FIELD_ERRORS';

export const GET_TODOS_BEGIN = "GET_TODOS_BEGIN";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_ERROR = "GET_TODOS_ERROR"

export const EDIT_TODO_BEGIN = "EDIT_TODO_BEGIN";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const EDIT_TODO_ERROR = "EDIT_TODO_ERROR";

export const CREATE_TODO_BEGIN = "CREATE_TODO_BEGIN";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_ERROR = "CREATE_TODO_ERROR";

export const DELETE_TODO_BEGIN = "DELETE_TODO_BEGIN";
export const DELETE_TODO_ERROR = "DELETE_TODO_ERROR";

export const CREATE_SET_BEGIN = "CREATE_SET_BEGIN";
export const CREATE_SET_SUCCESS = "CREATE_SET_SUCCESS";
export const CREATE_SET_ERROR = "CREATE_SET_ERROR";

export const GET_SETS_BEGIN = "GET_SETS_BEGIN";
export const GET_SETS_SUCCESS = "GET_SETS_SUCCESS";

export const GET_SET_BEGIN = "GET_SET_BEGIN";
export const GET_SET_SUCCESS = "GET_SET_SUCCESS";

export const SET_NOT_FOUND = "SET_NOT_FOUND"
export const SET_FOUND = "SET_FOUND"